import Head from 'next/head'
import Navbar from '../components/Navbar'
import Index from '../components/About/Index'
import Footer from '../components/Footer'
// import styles from '../styles/Home.module.css'

export default function About() {
  return (
    <>
      <Head>
        <title>Udaan Property Pvt Ltd - About</title>
        <meta name="description" content="Generated by Udaan Property Pvt Ltd" />
        <link rel="icon" href="/favicon.ico" />  
      </Head>
      <Navbar calledBy="about"/>
      <Index/>
      <Footer/>
    </>
  )
}
