import Head from 'next/head'
import Navbar from '../components/Navbar'
import Homepage from '../components/Homepage/Index'
// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Udaan Property Pvt Ltd</title>
        <meta name="description" content="Generated by Udaan Property Pvt Ltd" />
        <link rel="icon" href="/favicon.ico" />  
      </Head>
      <Navbar/>
      <main>
         <Homepage/>
      </main>
    </>
  )
}
