import Head from 'next/head'
import Navbar from '../components/Navbar'
import Homepage from '../components/Homepage/Index'
// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Udaan Property Pvt Ltd</title>
        <meta name="description" content="Generated by Udaan Property Pvt Ltd" />
        <link rel="icon" href="/favicon.ico" />        
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Gruppo&family=Squada+One&family=Satisfy&display=swap" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap" rel="stylesheet"/>
        <link href="/fonts/archer/style.css" rel="stylesheet"/>
        <link href="/fonts/plantin/style.css" rel="stylesheet"/>
      </Head>
      <Navbar/>
      <main>
         <Homepage/>
      </main>
    </>
  )
}
